version: '2'
services:
  atop:
    image: mhristof/ansible-1.9.4
    command: ansible-playbook -i 'localhost, ' -c local /etc/ansible/roles/atop/atop.yml
    volumes:
      - ./:/etc/ansible/roles/atop
