---
# tasks file for roles/atop

  - name: Disable atop service (will be replaced by ours)
    service:
      name: atop
      state: stopped
      enabled: false

  - name: remove init.d file
    file:
      path: /etc/init.d/atop
      state: absent
    tags:
      - init

  - name: deploy inid file
    template:
      src: etc/init/atop.conf
      dest: /etc/init/atop.conf
    notify:
      - restart atop
    tags:
      - init

  - name: deploy fix_atop file
    template:
      src: usr/local/bin/fix_atop.sh
      dest: /usr/local/bin/fix_atop.sh
      mode: 0700

  - name: deploy cron stuff
    template:
      src: etc/cron.d/atop
      dest: /etc/cron.d/atop
